# Used in terraform resource tagging
user: "{{user:id?anon}}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "tal"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "default"


# used for resource naming in various places
id: "{{user}}-metta-tal"
# where to put terraform and launchpad state/var/config files
files_path: .
# prefix for terraform/launchpad files to allow variations
files_prefix: "{{id}}"

# Path to the terraform plan to be used
terraform_plan: "{{mirantis:terraform.plans.prodeng.aws.v8}}"
# Prefix for terraform resources for identifcation and variations
resource_prefix: "{{id}}"
# AWS region for resources
aws_region: us-east-2

# perhaps not needed any more
cluster_name: "{{id}}"
# used to tag cluster resources for expiry
expire_duration: 72h

# Extra tags which should get assigned to any created resources
extra_tags:
  owner: "{{user:id?not-specified}}"
  tooling: metta

# The Linux platform to use for manager/worker/DTR replica nodes
# Typically overridden in a platform config variables file
platform_repo: public
platform: ubuntu_20.04

# mirantis app versions and sources
# typically overriden in a release config variables file
# mcr_repo_url: "https://repos.mirantis.com/"
mcr_repo_url: "https://s3.amazonaws.com/repos-internal.mirantis.com/"
mcr_channel: stable
mcr_version: 20.10.0
mcr_install_url_linux: "https://get.mirantis.com/"
mcr_install_url_windows: "https://get.mirantis.com/install.ps1"

mke_image_repo: docker.io/mirantis
mke_version: 3.4.0
# These are actually poor design, as we are putting app defaults in config
# in order to support easy overrides, in order to maintain an easy to read
# config only lunchpad.yaml config source.
# @TODO refactor how things like install flags work in launchpad
mke_install_nodeport_range: "32768-35535"
mke_install_defaultorchestrator: kubernetes

msr_image_repo: docker.io/mirantis
msr_version: 2.9.0

# machine/node counts to use
# typically overridden in a cluster config variables file
manager_count: 1
manager_type: t3.xlarge
manager_volume_size: 100
worker_count: 3
worker_type: t3.large
worker_volume_size: 100
windows_worker_count: 0
msr_count: 1
msr_type: t3.xlarge
msr_volume_size: 100

# SSH/RDP admin passwords for nodes
admin_password: orcaorcaorca
windows_administrator_password: "tfaws,,ABC..Example"
